#!/bin/bash
mkdir histLM_dataset
cd histLM_dataset
wget https://zenodo.org/record/4782245/files/flair.zip
unzip flair.zip
rm flair.zip
wget https://zenodo.org/record/4782245/files/bert.zip
unzip bert.zip
rm bert.zip
wget https://zenodo.org/record/4782245/files/fasttext.zip
unzip fasttext.zip
rm fasttext.zip
wget https://zenodo.org/record/4782245/files/word2vec.zip
unzip word2vec.zip
rm word2vec.zip
cd ..
exec "$@"
